[Settings]
  ID = "9b28ed47-6cfa-4057-becb-ae296f7c17ea"

[build]
    publish = "public"
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"
